import { SignInButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { CreatePostWizard } from "~/components/CreatePostWizard";
import { Feed } from "~/components/Feed";
import { api } from "~/utils/api";

const Home: NextPage = () => {

  const { isSignedIn, isLoaded: userLoaded } = useUser();
  api.posts.getPosts.useQuery();

  if(!userLoaded) return <div />;



  return (
    <>
      <Head>
        <title>Zelzazor&apos;s Chirp</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex flex-col">
        <nav className="p-4">
        { isSignedIn ? (
          <CreatePostWizard />
        ) : (
          <div className="flex gap-4 justify-between">
            <h2 className="text-2xl font-bold">Wanna share some ideas? Sign in!</h2>
            <SignInButton>
              <button className="bg-slate-400 px-6 py-2 rounded">Sign in</button>
            </SignInButton>
          </div>
        )}
        </nav>
        <section className="flex justify-center mt-4 grow">
          <Feed />
        </section>
        
        
      </main>
    </>
  );
};

export default Home;
